recipes/devel/bootstrap-sandbox.yaml, recipes/devel/git.yaml, recipes/devel/sandbox.yaml, recipes/net/curl.yaml
Without these changes building the embedded example failed to build with the error message:
```
CHECKOUT  work/demo/echo-chamber/src/1/workspace
fatal: Unable to find remote helper for 'https'
Step failed with return status 128; Command: git fetch -p origin
Call stack (most recent call first)
#0: Recipe demo::echo-chamber in checkoutSCM: dir:., url:https://github.com/BobBuildTool/bob-example-embedded-echo-chamber.git, line 29, in main
Build error: Build script ./work/demo/echo-chamber/src/1/checkout.sh returned with 128
Failed package: demo::linux+freertos/demo::vexpress/demo::initramfs/demo::echo-chamber
```
Afterwards, the checkout works fine:
```
CHECKOUT  work/demo/echo-chamber/src/1/workspace
From https://github.com/BobBuildTool/bob-example-embedded-echo-chamber
* [new branch] …
```
=> Compile git with cURL to enable HTTP(S) transport

recipes/utils/file.yaml
The earlier version suffered from https://bugs.gentoo.org/661508
=> utils/file: bump to 5.38

recipes/libs/gdbm.yaml
* prerequisite for other packages like python-dev
=> libs/gdbm: enabled libgdbm compat

recipes/libs/ncurses.yaml
* widec is prerequisite for for other packages, e.g. python3-dev
=> libs/ncurses: enabled widec, added BASEMENT_LIBS (static/shared) switch, small bugfixes

classes/cmake.yaml
=> classes/cmake: fixed typo, missing S for MAKE_TARGETS

classes/cmake.yaml
Some CMake scripts access this variable unconditionally, such as
libjpeg-turbo's. Looking at the official docs [1] they seem to be right
in the assumption that CMAKE_SYSTEM_PROCESSOR will always be set.
[1] https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html
=> classes/cmake: Set CMAKE_SYSTEM_PROCESSOR

recipes/devel/compat/gcc.yaml, recipes/devel/gcc.yaml
Installing in parallel can lead to files already existing, causing
errors like the following:
```
/usr/bin/install: cannot create regular file '/bob/d9a8abbafac9128d662477c77d7585af393f3b55/workspace/build/../install/usr/lib/gcc/x86_64-cross-linux-gnu/9.2.0/include/ssp/stdio.h': File exists
```
=> devel[/compat]/gcc: Install sequentially

recipes/libs/freetype.yaml
Unrelated changes (#128) revealed that this change is necessary. It must have been shadowed somehow with the old toolchain...
The error message was
```
[ 630] BUILD     libs::freetype-tgt - work/libs/freetype-tgt/x86_64-cross-linux-gnu/build/6/workspace
[ 630] |libs::freetype-tgt| cp: cannot stat '/bob/7e1a2c0b5bdf98f3a128373a90eaa634a9aa66fa/workspace/docs/markdown': No such file or directory
[ 630] |libs::freetype-tgt| configure: WARNING: using cross tools not prefixed with host triplet
[ 630] |libs::freetype-tgt| configure: error: cannot find native C compiler
[ 630] |libs::freetype-tgt| make: *** [/bob/7e1a2c0b5bdf98f3a128373a90eaa634a9aa66fa/workspace/builds/unix/detect.mk:89: setup] Error 1
[ 630] |libs::freetype-tgt| Step failed with return status 2; Command: $1/configure …
```
=> libs/freetype: Add host toolchain to build tools

recipes/libs/libcap.yaml
This was needed for me in order to get cross-compilation to work, otherwise it would fail with an error message about an exec format error in one of the tools used while building.
Also, upgrade to 2.64 whilst we're at it.
=> libs/libcap: Provide host toolchain

recipes/devel/git.yaml
First things first: The final goal is to have Git as a tool.
With that being said, compiling for the sandbox fails because the static version of the `crypto` lib needs `dl`, as stated in its `pkg-config` file (as `Libs.private`). As Git's `Makefile` doesn't use `pkg-config` but rather hard-coded compiler flags, the needed `-ldl` switch is missing when linking statically. With the changes presented here, Git can be build as a tool and works without any obvious problems. Of course, this change set cannot be the final solution.
My question is: where would be an appropriate place to put that `-ldl`? Patching the `Makefile`? But what about the non-static build? Or patching the `Makefile` conditionally?
=> devel/git: Provide Git as a tool

recipes/libs/glibc/0003-glibcextract.py-add-compile_c_snippet.diff, recipes/libs/glibc/0004-linux-use-compile_c_snippet-to-check-linux-pidfd.h-availability.diff, recipes/libs/glibc/0005-linux-mimic-kernel-defition-for-block_size.diff, recipes/libs/glibc/0006-linux-use-compile_c_snippet-to-check-linux-mount.h-availability.diff, recipes/libs/glibc/0007-linux-fix-sys-mount.h-usage-with-kernel-headers.diff
Without these some packages fail to compile because glibc redefines enums already defined by the kernel. The patches are upstream already and part of the next glibc release.
This fixes the issues I've mentioned in my [previous comment](https://github.com/BobBuildTool/basement/pull/160#issuecomment-1338986534).
=> libs/glibc: Backport header checks

plugins/multiarch.py
The $(host-arch) function returns what the Linux kernel expects for the ARCH environment variable. This is not compatible to the autoconf triplet. For example the "aarch64-linux-gnu" triplet corresponds to the "arm64" ARCH.
Fixes #162.
=> multiarch: fix autoconf triplet for aarch64

recipes/devel/patch.yaml
This minor version upgrade has a crucial fix that newly created files have the correct mode as specified in the patch. Because 849b79a6932687079d5f9277f26177f7cf40eb81 introduced a patch in libs::glibc that creates an executable file, the basement repo actually ran into this bug.
Even more problematic, the latest patch version was released 5 years ago, so that basically all distros already ship the latest version. This has the effect that almost all basement artifact downloads fail. The reason is the distributed Jenkins build. The checkout of libs::glibc is done multiple times. Once without sandbox and then in the bootstrap-sandbox. Because of the old patch version in the bootstrap-sandbox the checkout got inconsistent.
=> devel/patch: bump to 2.7.6

recipes/devel/compat/gcc.yaml, recipes/devel/compat/gcc/0003-fix-canadian-cross-includes.patch
The canadian cross build of libstdc++ incorrectly adds /usr/include to the include paths. This calls for trouble. This is actually a known bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71212
Fixes #185.
=> devel/compat/gcc: fix canadian cross build

recipes/libs/openssl.yaml
The path to openssl version 1.1.1.i has been postponed. Adapt the URL to the new path.
=> openssl: fix broken checkout url

classes/autoconf.yaml, recipes/devel/autoconf.yaml, recipes/devel/autoconf/0001-dont-add-dirty-to-version.patch, recipes/devel/autoconf/0002-relocatable-autoconf.patch
Prevent spurious reconfigurations at build time. And while at it, bump to latest version.
=> Fix autoreconf

classes/sandbox.yaml
the namespace-sandbox in bob 0.24.0 creates its own devpts mount
=> Remove /dev/pts mount from sandbox

classes/install.yaml, default.yaml, recipes/devel/compat/cross-toolchain.yaml, recipes/devel/cross-toolchain.yaml, recipes/devel/gcc.yaml, recipes/devel/host-compat-toolchain.yaml
The old selection of shared libraries for the target relied on the naming. This is unreliable. Instead, look for files and create SONAME links as necessary.
=> Fix target installation of shared libraries

classes/cpackage.yaml
The cpackageLibraryTypeCheck function can be used to get a correct list of input items based on the library type being build. It has two input parameters, the first being the item for the static library case and the second parameter describing an item for the shared library case. Use it like this:
BUILD_TARGETS=$(cpackageLibraryTypeCheck libstatic.a libshared.so)
=> cpackage: add cpackageLibraryTypeCheck convenience function

classes/meson.yaml
Fix some warnings from meson about features we use which are deprecated.
=> Fix deprecated warnings when using meson

recipes/devel/autoconf/0003-config-sub-add-l4re.patch
Add the L4Re OS to the config.sub such that it is added to projects when they run autoconf.
=> autoconf: Add L4Re OS

recipes/devel/fakeroot.yaml
Fakeroot opens its library manually by looking for libfakeroot.so. However, the installed library name is libfakeroot-0.so. autotoolsPackageTgt ignores the installed symlink, because the SONAME is libfakeroot-0. Add the symlink back, so the fakeroot binary finds the library.
=> Add fakeroot library symlink

recipes/libs/openssl.yaml
This bumps openssl to 3.3.1 and removes a variable assignment that is not needed anymore.
=> openssl version bump and cleanup

recipes/libs/openssl/0002-Adapt-all-the-exporter-files-to-the-new-vars-from-ut.patch, recipes/libs/openssl/0003-Fix-cmake-generator.patch, recipes/libs/openssl/0004-fix-exporters-cmake-OpenSSLConfig.cmake.in-to-work-f.patch, recipes/libs/openssl/0005-Give-util-mkinstallvars.pl-more-fine-grained-control.patch, recipes/libs/openssl/0006-fix-util-mkinstallvars.pl-mistreated-LDLIBS-on-Unix-.patch, recipes/libs/openssl/0007-fix-for-exporters-to-work-for-build-config-there-may.patch, recipes/libs/openssl/0008-exporters-for-pkg-config-align-with-the-changes-for-.patch
OpenSSL 3.3 introduced a regression that caused the pkg-config files to not be relocatable any more. Cherry pick the fixes from upstream.
See https://github.com/openssl/openssl/issues/24298.
=> libs/openssl: fix pkg-config files

classes/install.yaml, classes/pkg-config.yaml
Some packages install their pc file(s) into /usr/share/pkgconfig. Make sure they are installed and useable.
=> Add /usr/share/pkgconfig to PKG_CONFIG search path

recipes/core/coreutils.yaml, recipes/core/coreutils/0001-mcel-port-to-uClibc-ng.patch, recipes/core/coreutils/0002-gcc14-uclibc-mbszero-fix.patch
Pick the change from gnulib making coreutils compile with uclibc. Plus add some header include fixes for uclibc that trigger with gcc14. Might need to be discussed.
=> core/coreutils: Pick uclibc compatibility patch + uclibc-mbszero

classes/sandbox.yaml
Actually some tools require code page converting functionality when used as host tools. One of those are the mtools which try to convert to some fat specific code pages and fail when the gconv libraries are not there.
=> sandbox: don't remove the code page converting libs

recipes/devel/binutils.yaml, recipes/devel/cross-toolchain.yaml, recipes/devel/gcc.yaml, recipes/devel/meson.yaml
This adds support for building a cross-toolchain with ada-language enabled. 
As a gnat-compiler is needed to build gcc with gnat this needs to be setup before. There is a ada-layer at https://github.com/rhubert/layers-ada which uses `alr` to download the gnat-compiler from adacore. 
Using the gnat-toolchain from this layer will not change the target / host-toolchain setting. Instead it provides a `gnat-host-toolchain` and a `gnat-target-toolchain` (based on gcc-13.2). 
This is because we still want to use the `host-compat-toolchain` for all non-ada components - otherwise these tools won't be run-able on older systems.
OTOH we don't want to build + use the `host-compat-toolchain` with ada and use this for the ada-host-tools because they are using the latest ada-features + fixes.
To build a …
=> initial Ada support

classes/basement/rootrecipe.yaml, recipes/core/util-linux.yaml, recipes/devel/bootstrap-sandbox.yaml, recipes/devel/sandbox.yaml
Add a new generic bin target and install only libs in *-tgt. Some apps depend on the libs and don't necessarily need the executables as well. Also there was a provideDeps missing.
=> core::util-linux: bump to v2.40.2

plugins/msbuild.py
Use a raw-string here to avoid
plugins/msbuild.py:18: SyntaxWarning: invalid escape sequence '\*'
'-find', 'MSBuild\**\Bin\MSBuild.exe',
=> plugins/msbuild: fix SyntaxWarning

recipes/devel/ninja.yaml
Ninja requires itself to be built. So for cross-compilation, we need a bootstrap ninja that can be executed on the host.
=> devel/ninja: enable cross compilation

classes/cmake.yaml
Recognize "l4re" as a toolchain target, pointing to Linux for the time being.
=> classes/cmake: Add L4Re to toolchain

classes/python3-usr.yaml, classes/python3-usr_checkout.yaml
65cedc9 makes python usabe in checkoutScripts. This produces different checkoutVariants for recipes where the python part is only needed for one multiPackage but not for another:
```
checkoutSCM:
...
multiPackage:
foo:
python:
inherit: [python3-usr]
```
Revert 65cedc9 and add a separate python3-usr-checkout class to avoid this.
=> python3-usr: provide sepeate class for checkout usage

plugins/config.py
The schema error must be caught in the Bob plugin class, not in an inner validator. While at it, print some error message to aid debugging.
=> config: fix schema validation

recipes/python/installer.yaml, recipes/python/installer/0001-fix-shebang.patch
The installer did put the absolute path of the Python interpreter in the generated scripts. This completely breaks binary artifacts. Instead, rely on python3 being in the PATH.
=> python::installer: fix shebang generation

classes/strip.yaml
The file command reports ELF files with the setuid bit is set as
setuid ELF 64-bit LSB pie executable [...] with debug_info, not stripped
Fix the condition to cover these as well.
=> strip: fix stripping of setuid ELF files
